version: "3.5"
services:
    numbemu-s3:
        build: 
          context:  ./s3-service/
        hostname: api-nubemu
        environment:
          - ASPNETCORE_URLS=http://+:80
        ports:
            - 8080:80
